### ISSUE TITLE
Images of symbols 

### ISSUE THREAD

**Issue by ImOnlyYisus** [505e06b2/Black-Ops-2-Emblem-Editor#1]
Hello, the project is awesome!, 
One question, how did you export all symbols from bo2?, i want to try do a emblem editor of bo3 but i dont know how to export or get all images.

**Comment by 505e06b2** [comment]
It's been quite some time since I did it, but I do remember having to essentially greenscreen the symbols - a big green square in the BG, then size up another symbol in white and keep replacing it with each symbol; a lot of work!
If you take consistent screenshots, you should be able to automate cropping and replacing the background (with imagemagick or Python's PIL for example)

**Comment by ImOnlyYisus** [comment]
Wow, it sounds hard.
Thanks for helping, i will try to look a way than don't take all my time.
